[mgr]
ratio           = [ 1, 3, 4 ]
show_hidden     = true
linemode        = "size"

[preview]
cache_dir       = "~/.cache/yazi"
wrap            = "no"
max_width       = 1920
max_height      = 1080
tab_size        = 2
image_filter    = "triangle"
image_quality   = 75
ueberzug_scale  = 1
ueberzug_offset = [ 0, 0, 0, 0 ]
windows-paddinx-x = 0
